
-- Q1-1
SELECT e.DEPTNO , d.DNAME , e.ENAME , sal
FROM EMP e , DEPT d 
WHERE SAL > 2000 AND e.DEPTNO = d.DEPTNO 
ORDER BY e.DEPTNO 

-- Q1-2
SELECT DEPTNO , d.DNAME , e.ENAME , sal
FROM EMP e NATURAL JOIN DEPT d 
WHERE sal > 2000
ORDER BY DEPTNO 

SELECT e.DEPTNO , d.DNAME , e.ENAME , sal
FROM EMP e JOIN DEPT d ON (e.DEPTNO = d.DEPTNO)
WHERE sal > 2000
ORDER BY DEPTNO 

-- Q2-1
SELECT e.DEPTNO , d.DNAME , TRUNC( avg(sal) ), max(sal), min(sal), COUNT(*) 
FROM EMP e , DEPT d 
WHERE e.DEPTNO = d.DEPTNO 
GROUP BY e.DEPTNO , d.DNAME 
ORDER BY e.DEPTNO 

-- Q2-2
SELECT DEPTNO , d.DNAME , AVG(sal) 
FROM EMP e JOIN DEPT d using (DEPTNo)
GROUP BY DEPTNO , d.DNAME 

-- Q3-1
SELECT d.DEPTNO , d.DNAME , e.EMPNO , JOB , SAL 
FROM EMP e ,DEPT d 
WHERE e.DEPTNO(+) = d.DEPTNO 
ORDER BY e.DEPTNO 

-- Q3-2
SELECT d.DEPTNO , d.DNAME , e.EMPNO , JOB , SAL 
FROM EMP e RIGHT OUTER JOIN DEPT d ON (D.DEPTNO = E.DEPTNO)
ORDER BY e.DEPTNO 


SELECT e.EMPNO , e.ENAME , e.JOB ,e.MGR ,e.HIREDATE ,e.SAL ,e.COMM , e.DEPTNO ,d.DNAME , d.LOC 
FROM EMP e JOIN DEPT d on (e.DEPTNO = d.DEPTNO)
WHERE SAL <= 3000



SELECT *
FROM emp e1 LEFT OUTER JOIN emp e2 ON (e1.mgr = e2.EMPNO)
