SELECT AVG(SAL), '10' AS DEPTNO FROM EMP WHERE DEPTNO = 10
UNION ALL
SELECT AVG(SAL), '20' AS DEPTNO FROM EMP WHERE DEPTNO = 20
UNION ALL
SELECT AVG(SAL), '30' AS DEPTNO FROM EMP WHERE DEPTNO = 30

SELECT AVG(SAL), DEPTNO FROM EMP GROUP BY DEPTNO;

SELECT DEPTNO, JOB, AVG(SAL) FROM EMP GROUP BY DEPTNO, JOB ORDER BY DEPTNO, JOB;

SELECT ENAME, DEPTNO, AVG(SAL) FROM EMP GROUP BY ENAME, DEPTNO ;

SELECT DEPTNO, JOB, AVG(SAL) 
FROM EMP 
GROUP BY DEPTNO , JOB 
HAVING AVG(SAL) >= 2000 
ORDER BY DEPTNO , JOB;


SELECT DEPTNO, JOB, AVG(SAL)
	FROM EMP
GROUP BY DEPTNO, JOB 
	HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO, JOB;

SELECT DEPTNO, JOB, AVG(SAL)
	FROM EMP
	WHERE SAL <= 3000
GROUP BY DEPTNO, JOB 
	HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO, JOB;

SELECT *
	FROM EMP, DEPT
ORDER BY EMPNO;

SELECT *
	FROM EMP, DEPT
	WHERE EMP.DEPTNO = DEPT.DEPTNO
ORDER BY EMPNO;

SELECT *
	FROM EMP E, SALGRADE S
	WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL ;

SELECT E.EMPNO 
	FROM EMP E, EMP E2
WHERE E.MGR = E2.EMPNO;


-- Q1
SELECT E.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, SAL
	FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND SAL > 2000
GROUP BY E.DEPTNO, D.DNAME, E.ENAME  
ORDER BY DEPTNO ; 

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND E.SAL > 2000;
  
  SELECT * FROM DEPT;
 

  UPDATE FROM DEPT WHERE DEPTNO = 10;
  DELETE FROM DEPT WHERE DEPTNO  = 10;
UPDATE DEPT SET DEPTNO = 'DEPTNO' WHERE DEPTNO = 10;


SELECT * FROM DEPT;
SELECT * FROM EMP
